# Generated by Django 5.1.1 on 2024-10-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, upload_to='artist_cover'),
        ),
        migrations.AddField(
            model_name='band',
            name='cover',
            field=models.ImageField(blank=True, upload_to='band_cover'),
        ),
    ]
