# Generated by Django 5.1.1 on 2024-10-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_cover_band_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_cover',
            new_name='cover',
        ),
    ]
