# Generated by Django 5.1.1 on 2024-10-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_song_cover_song_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='recorder',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
