# Generated by Django 5.1.1 on 2024-10-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_length_alter_album_recorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_cover',
            new_name='cover',
        ),
    ]
