# Generated by Django 5.1.1 on 2024-10-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_album_cover_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
            preserve_default=False,
        ),
    ]
