# Generated by Django 5.1.1 on 2024-10-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_event_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ManyToManyField(to='music.band'),
        ),
        migrations.AddField(
            model_name='event',
            name='band',
            field=models.ManyToManyField(to='music.band'),
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ManyToManyField(to='music.band'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ManyToManyField(to='music.artist'),
        ),
    ]
