# Generated by Django 5.1.1 on 2024-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_artist_is_band_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.ManyToManyField(blank=True, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ManyToManyField(blank=True, to='music.band'),
        ),
    ]
