# Generated by Django 5.1.1 on 2024-10-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_event_artist_alter_event_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='band',
            new_name='bands',
        ),
    ]
