# Generated by Django 5.1.1 on 2024-10-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_rename_artist_event_artists_rename_band_event_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistgallery',
            name='cover',
            field=models.ImageField(default='', upload_to='gallery_covers'),
            preserve_default=False,
        ),
    ]
