# Generated by Django 5.1.1 on 2024-10-10 02:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_artistgallery_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.event')),
            ],
        ),
    ]
