# Generated by Django 5.1.1 on 2024-10-10 02:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_eventtestimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='event_covers')),
                ('detail', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.event')),
                ('images', models.ManyToManyField(to='music.galleryimage')),
            ],
        ),
    ]
